## DATASCIENCE BOOTCAMP 
WEEK 2
NUMPY

In [1]:
!pip3 install numpy

In [8]:
import numpy as np


In [18]:
A=np.array([1,2,3,4,5,3,9])
B=np.array([6,7,8,9,10,1,6])

#horizontalStacking
c=np.hstack((A,B))

#verticalStacking
d=np.vstack((A,B))

print(c)
print(d)

#printCommon

common=np.intersect1d(a,b)
print(common)


#printingWithinRange

WithinRange=B[(B>=5) & (B<=10)]
print(WithinRange)

[ 1  2  3  4  5  3  9  6  7  8  9 10  1  6]
[[ 1  2  3  4  5  3  9]
 [ 6  7  8  9 10  1  6]]
[1 9]
[ 6  7  8  9 10  6]


In [ ]:
import urllib.request

# Step 1: Open the URL directly
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

with urllib.request.urlopen(url) as f:
    iris_2d = np.genfromtxt(f, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Step 2: Apply filtering
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[condition]

print("Filtered rows where petallength > 1.5 and sepallength < 5.0:\n")
print(filtered_rows)


Filtered rows where petallength > 1.5 and sepallength < 5.0:

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
